# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ExcuseClub' do

pod 'HockeySDK'
pod 'AFNetworking'
pod 'Reachability'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'PureLayout'
pod 'FontAwesome'
pod 'ionicons'
pod "AMSlideMenu", "~> 1.5.4"
pod 'SDVersion'
pod 'SDWebImage', '~>3.8'

end
